Mount the Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Load the packages

In [2]:
import pandas as pd
import re

In [9]:
PROJECT_DIR = '/content/drive/MyDrive/product_search_engine'
DATA_DIR = f"{PROJECT_DIR}/data"

Load the dataset

In [10]:
df = pd.read_csv(f"{DATA_DIR}/cleaned_products.csv")
df.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,images_path
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,/content/drive/MyDrive/product_search_engine/d...
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,/content/drive/MyDrive/product_search_engine/d...
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,/content/drive/MyDrive/product_search_engine/d...
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,/content/drive/MyDrive/product_search_engine/d...
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,/content/drive/MyDrive/product_search_engine/d...

### Clean the text

In [11]:
def clean_text(text):
  text = text.lower() # Convert the text into lowercase
  text = re.sub(r"[^a-z0-9\s]", "", text) # Remove punctuations and special sybols
  text = re.sub(r"\s+", " ", text).strip() # Remove extra whitespace

  return text

Add metadata to the input text

In [12]:
df['text_input'] = (
    df['productDisplayName'].fillna('') + '. ' +
    "Category : " + df['masterCategory'] + '. ' +
    "Type : " + df['articleType'] + '. ' +
    "Color: " + df['baseColour'].fillna('')
    )

In [14]:
# Remove the punctuations, special symbols, and whitespaces
df['text_input'] = df['text_input'].apply(clean_text)

In [16]:
df.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,images_path,text_input
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,/content/drive/MyDrive/product_search_engine/d...,turtle check men navy blue shirt category appa...
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,/content/drive/MyDrive/product_search_engine/d...,peter england men party blue jeans category ap...
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,/content/drive/MyDrive/product_search_engine/d...,titan women silver watch category accessories ...
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,/content/drive/MyDrive/product_search_engine/d...,manchester united men solid black track pants ...
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,/content/drive/MyDrive/product_search_engine/d...,puma men grey tshirt category apparel type tsh...

Save the input text processed file

In [17]:
OUT_PATH = f"{DATA_DIR}/text_processed.csv"
df.to_csv(OUT_PATH, index=False)